# Generated by Django 5.0.6 on 2024-05-17 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discount",
            old_name="percentage",
            new_name="discount",
        ),
        migrations.RenameField(
            model_name="price",
            old_name="original_price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="price",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="price",
            name="discounted_price",
        ),
    ]
