# Generated by Django 5.0.6 on 2024-05-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_rename_percentage_discount_discount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="price",
            old_name="price",
            new_name="original_price",
        ),
        migrations.AddField(
            model_name="price",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
