# Generated by Django 5.0.6 on 2024-05-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_rename_price_price_original_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="description",
            field=models.CharField(
                blank=True,
                default="Add your description here",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="images",
            field=models.ImageField(default="#", upload_to=""),
        ),
        migrations.AddField(
            model_name="price",
            name="title",
            field=models.CharField(default="Enter your title", max_length=120),
        ),
    ]
