# Generated by Django 5.0.6 on 2024-05-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_price_description_price_images_price_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="price",
            name="images",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="price",
            name="title",
            field=models.CharField(max_length=120),
        ),
    ]
