# Generated by Django 5.0.6 on 2024-05-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_price_description_alter_price_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="images",
            field=models.CharField(max_length=1000),
        ),
    ]
